namespace: kube-system
resources:
  - helmrepo.yaml
  - helmrelease.yaml
  - ciliumloadbalancerippool.yaml
  - ciliuml2announcementpolicy.yaml
configMapGenerator:
  - name: cilium-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
