bootstrap:
  wait_for_computes:
    enabled: true

conf:
  ceph:
    enabled: true
  nova:
    DEFAULT:
      # Increase timeouts for volume creation
      # Number of retries to wait for volume creation (default: 60)
      block_device_allocate_retries: 120
      # Interval in seconds between each retry (default: 3)
      block_device_allocate_retries_interval: 10
    vnc:
      novncproxy_base_url: http://openstack.rpcu.vpn/vnc/
network:
  osapi:
    ingress:
      public: false
  metadata:
    ingress:
      public: false
images:
  tags:
    bootstrap: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    db_drop: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    db_init: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    ks_user: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    ks_service: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    ks_endpoints: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    nova_api: "quay.io/airshipit/nova:2025.2-ubuntu_noble"
    nova_cell_setup: "quay.io/airshipit/nova:2025.2-ubuntu_noble"
    nova_cell_setup_init: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    nova_compute: "quay.io/airshipit/nova:2025.2-ubuntu_noble"
    nova_compute_ssh: "quay.io/airshipit/nova:2025.2-ubuntu_noble"
    nova_conductor: "quay.io/airshipit/nova:2025.2-ubuntu_noble"
    nova_db_sync: "quay.io/airshipit/nova:2025.2-ubuntu_noble"
    nova_novncproxy: "quay.io/airshipit/nova:2025.2-ubuntu_noble"
    nova_novncproxy_assets: "quay.io/airshipit/nova:2025.2-ubuntu_noble"
    nova_scheduler: "quay.io/airshipit/nova:2025.2-ubuntu_noble"
    nova_spiceproxy: "quay.io/airshipit/nova:2025.2-ubuntu_noble"
    nova_spiceproxy_assets: "quay.io/airshipit/nova:2025.2-ubuntu_noble"
    nova_service_cleaner: "quay.io/airshipit/ceph-config-helper:latest-ubuntu_jammy"
endpoints:
  cluster_domain_suffix: openstack.local
  compute:
    host_fqdn_override:
      public:
        host: openstack.rpcu.vpn
        path: /nova
    scheme:
      public: http
    port:
      api:
        public: 80
  compute_metadata:
    host_fqdn_override:
      public:
        host: openstack.rpcu.vpn
        path: /nova/metadata
    scheme:
      public: http
    port:
      metadata:
        public: 80
  compute_novnc_proxy:
    host_fqdn_override:
      public:
        host: openstack.rpcu.vpn
        path: /vnc/vnc_auto.html
    scheme:
      public: http
    port:
      novnc_proxy:
        public: 80
