images:
  tags:
    prometheus_rabbitmq_exporter_helm_tests: quay.io/airshipit/openstack-client:2025.2-ubuntu_noble
    rabbitmq_init: quay.io/airshipit/openstack-client:2025.2-ubuntu_noble
endpoints:
  cluster_domain_suffix: openstack.local
pod:
  replicas:
    server: 1
network:
  management:
    ingress:
      classes:
        namespace: "contour"
