images:
  tags:
    bootstrap: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    db_init: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    db_drop: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    ks_user: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    ks_service: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    ks_endpoints: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    neutron_db_sync: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
    neutron_dhcp: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
    neutron_l3: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
    neutron_l2gw: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
    neutron_linuxbridge_agent: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
    neutron_metadata: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
    neutron_ovn_metadata: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
    neutron_openvswitch_agent: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
    neutron_server: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
    neutron_rpc_server: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
    neutron_bagpipe_bgp: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
    neutron_netns_cleanup_cron: "quay.io/airshipit/neutron:2025.2-ubuntu_noble"
endpoints:
  cluster_domain_suffix: openstack.local
conf:
  neutron:
    DEFAULT:
      l3_ha: False
      max_l3_agents_per_router: 1
  auto_bridge_add:
    br-ex: eno1
  plugins:
    ml2_conf:
      ml2_type_flat:
        flat_networks: public
    openvswitch_agent:
      ovs:
        bridge_mappings: public:br-ex
manifests:
  configmap_bin: false
