images:
  tags:
    bootstrap: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    db_init: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    db_drop: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    keystone_api: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
    keystone_bootstrap: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    keystone_credential_rotate: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
    keystone_credential_setup: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
    keystone_db_sync: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
    keystone_domain_manage: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
    keystone_fernet_rotate: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
    keystone_fernet_setup: "quay.io/airshipit/keystone:2025.2-ubuntu_noble"
    ks_user: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
network:
  api:
    ingress:
      public: true
      classes:
        namespace: "contour"
        cluster: "contour"
      annotations:
        cert-manager.io/cluster-issuer: "root-rpcu"
        projectcontour.io/rewrite-target: "/"
endpoints:
  cluster_domain_suffix: openstack.local
  identity:
    host_fqdn_override:
      public:
        host: openstack.rpcu.vpn
        path: /keystone
    scheme:
      public: http
    port:
      api:
        public: 80
