namespace: openstack
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: glance-values
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true
patches:
  - path: patch-ks-endpoints-job.yaml
