images:
  pull_policy: IfNotPresent
  tags:
    placement: "quay.io/airshipit/placement:2025.2-ubuntu_noble"
    ks_user: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    ks_service: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    ks_endpoints: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    db_init: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    db_drop: "quay.io/airshipit/openstack-client:2025.2-ubuntu_noble"
    placement_db_sync: "quay.io/airshipit/placement:2025.2-ubuntu_noble"
    dep_check: "quay.io/airshipit/kubernetes-entrypoint:latest-ubuntu_jammy"
    image_repo_sync: "docker.io/docker:17.07.0"
conf:
  placement:
    DEFAULT:
      public_endpoint: http://openstack.rpcu.vpn/placement
network:
  api:
    ingress:
      public: false
dependencies:
  static:
    db_sync:
      jobs:
        - placement-db-init
endpoints:
  cluster_domain_suffix: openstack.local
  placement:
    host_fqdn_override:
      public:
        host: openstack.rpcu.vpn/placement
    scheme:
      public: http
    port:
      api:
        public: 80
