apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: root-rpcu
  name: rook-ceph-mgr-dashboard
  namespace: rook-ceph
spec:
  ingressClassName: contour
  rules:
    - host: ceph.rpcu.vpn
      http:
        paths:
          - backend:
              service:
                name: rook-ceph-mgr-dashboard
                port:
                  number: 7000
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - ceph.rpcu.vpn
      secretName: ceph-dashboard-tls-secret
