resources:
  - ceph-adapter-rook.yaml
  - cert-manager.yaml
  - cert-manager-issuer.yaml
  - cilium.yaml
  - contour.yaml
  - flux-operator.yaml
  - rook.yaml
  - openstack-ns.yaml
  - openstack-rabbitmq.yaml
  - openstack-mariadb.yaml
  - openstack-memcached.yaml
  - openstack-keystone.yaml
  - openstack-placement.yaml
  - openstack-glance.yaml
  - openstack-cinder.yaml
  - openstack-openvswitch.yaml
  - openstack-contour.yaml
  - openstack-libvirt.yaml
  - openstack-neutron.yaml
  - openstack-nova.yaml
  - openstack-horizon.yaml
  - openstack-ingress.yaml
  - fluxcd/
