resources:
  - ceph-adapter-rook.yaml
  - cert-manager.yaml
  - internal-issuer.yaml
  - cilium.yaml
  - contour.yaml
  - flux-operator.yaml
  - rook.yaml
  - openstack-rabbitmq.yaml
  - openstack-mariadb.yaml
  - openstack-memcached.yaml
  - fluxcd/
